apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  labels:
    app: frontend-app
spec:
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  selector:
    app: frontend-app
  type: LoadBalancer

# 

# apiVersion: v1
# kind: Service
# metadata:
#   name: frontend-service
#   selector:
#     app: frontend-learner-mgmt-app
#   ports:
#     - protocol: TCP
#       port: 80
#       targetPort: 80
#   type: ClusterIP