apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.serviceName}}
  labels:
    app: {{ .Values.service.app_name}}
spec:
  ports:
   - protocol: {{ .Values.service.protocol}}
     port: {{ .Values.service.port}}
     targetPort: {{ .Values.service.targetPort}}
  selector:
    app: {{ .Values.service.app_name}}
  type: {{ .Values.type}}