#Frontend Deployment-Related Variables
replicaCount: 2
deployment:
  app_name: frontend-app

ports:
  containerPort: 80

containers:
  image: mbans7a1/front_end_repo:frontendimgv1

env:
  name: VITE_API_BASE_URL
  url: http://aa74245c15ecd43b9a073b66b730d426-1003970181.eu-west-2.elb.amazonaws.com:8080

#Frontend Service-Related Variables

service:
  serviceName: frontend-service
  app_name : frontend-app
  port: 80
  targetPort: 80
  protocol: TCP

type: LoadBalancer


