#Backend Deployment-Related Variables
replicaCount: 2
deployment:
  app_name: backend-app

ports:
  containerPort: 8080

containers:
  image: mbans7a1/back_end_repo:backendimgv1


#Backend Service-Related Variables

service:
  serviceName: backend-service
  app_name : backend-app
  port: 8080
  targetPort: 8080
  protocol: TCP

type: LoadBalancer

#Backend Actuator variables

# livenessProbe:
#   httpHeaderName: Custom-Header
#   value: ""
#   initialDelaySeconds: 15
#   periodSeconds:  15
#   path: actuator/health
#   port: 8080

# readinessProbe:
#   httpHeaderName:  User-Agent
#   value: ""
#   initialDelaySeconds: 10
#   periodSeconds:  10
#   path: actuator/health
#   port: 8080