apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: backend-learner-mgmt-app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: NodePort